on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@master
    
    - name: Login
      uses: okteto/login@master
      with:
        token: ${{ secrets.OKTETO_TOKEN }}

    - name: Activate Namespace
      uses: okteto/namespace@master
      with:
        namespace: gustavoortega
    
    - name: Deploy App
      uses: okteto/apply@master
      with:
        namespace: gustavoortega
        manifest: deployment/deployment.yaml
    
    - name: Push
      uses: okteto/push@master
      with:
        namespace: gustavoortega
     
    - name: Sleep for 30 seconds
      uses: jakejarvis/wait-action@v0.1.0
      with:
        time: '30s'
    
    - name: Verify
      uses: srt32/uptime@v0.2
      with:
        url-to-hit: "https://nginx-deployment-gustavoortega.cloud.okteto.net/"
        expected-statuses: "200"
